// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CompleteOnboardingReducer from "../complete_onboarding_reducer";
import ConsumeRestoreResultReducer from "../consume_restore_result_reducer";
import CreateClassroomReducer from "../create_classroom_reducer";
import CreateRecoveryKeyReducer from "../create_recovery_key_reducer";
import CreateTransferCodeReducer from "../create_transfer_code_reducer";
import DeletePlayerReducer from "../delete_player_reducer";
import EndClassSprintReducer from "../end_class_sprint_reducer";
import EndSessionReducer from "../end_session_reducer";
import GetClassRecoveryCodesReducer from "../get_class_recovery_codes_reducer";
import GetMyRecoveryCodeReducer from "../get_my_recovery_code_reducer";
import IssueProblemReducer from "../issue_problem_reducer";
import JoinClassroomReducer from "../join_classroom_reducer";
import LeaveClassroomReducer from "../leave_classroom_reducer";
import MarkRecoveryEmailedReducer from "../mark_recovery_emailed_reducer";
import MigrateRecomputeTiersReducer from "../migrate_recompute_tiers_reducer";
import MigrateRecomputeTiersV2Reducer from "../migrate_recompute_tiers_v_2_reducer";
import MigrateResetWeightsReducer from "../migrate_reset_weights_reducer";
import MigrateSeedBestScoresReducer from "../migrate_seed_best_scores_reducer";
import MigrateSeedExtendedPairsReducer from "../migrate_seed_extended_pairs_reducer";
import MigrateSeedExtendedStatsReducer from "../migrate_seed_extended_stats_reducer";
import NextProblemReducer from "../next_problem_reducer";
import RegenerateRecoveryKeyReducer from "../regenerate_recovery_key_reducer";
import RegisterReducer from "../register_reducer";
import RestoreAccountReducer from "../restore_account_reducer";
import SetExtendedModeReducer from "../set_extended_mode_reducer";
import SetLearningTierReducer from "../set_learning_tier_reducer";
import SetUsernameReducer from "../set_username_reducer";
import StartClassSprintReducer from "../start_class_sprint_reducer";
import StartSessionReducer from "../start_session_reducer";
import SubmitAnswerReducer from "../submit_answer_reducer";
import ToggleClassroomVisibilityReducer from "../toggle_classroom_visibility_reducer";
import UseTransferCodeReducer from "../use_transfer_code_reducer";

export type CompleteOnboardingParams = __Infer<typeof CompleteOnboardingReducer>;
export type ConsumeRestoreResultParams = __Infer<typeof ConsumeRestoreResultReducer>;
export type CreateClassroomParams = __Infer<typeof CreateClassroomReducer>;
export type CreateRecoveryKeyParams = __Infer<typeof CreateRecoveryKeyReducer>;
export type CreateTransferCodeParams = __Infer<typeof CreateTransferCodeReducer>;
export type DeletePlayerParams = __Infer<typeof DeletePlayerReducer>;
export type EndClassSprintParams = __Infer<typeof EndClassSprintReducer>;
export type EndSessionParams = __Infer<typeof EndSessionReducer>;
export type GetClassRecoveryCodesParams = __Infer<typeof GetClassRecoveryCodesReducer>;
export type GetMyRecoveryCodeParams = __Infer<typeof GetMyRecoveryCodeReducer>;
export type IssueProblemParams = __Infer<typeof IssueProblemReducer>;
export type JoinClassroomParams = __Infer<typeof JoinClassroomReducer>;
export type LeaveClassroomParams = __Infer<typeof LeaveClassroomReducer>;
export type MarkRecoveryEmailedParams = __Infer<typeof MarkRecoveryEmailedReducer>;
export type MigrateRecomputeTiersParams = __Infer<typeof MigrateRecomputeTiersReducer>;
export type MigrateRecomputeTiersV2Params = __Infer<typeof MigrateRecomputeTiersV2Reducer>;
export type MigrateResetWeightsParams = __Infer<typeof MigrateResetWeightsReducer>;
export type MigrateSeedBestScoresParams = __Infer<typeof MigrateSeedBestScoresReducer>;
export type MigrateSeedExtendedPairsParams = __Infer<typeof MigrateSeedExtendedPairsReducer>;
export type MigrateSeedExtendedStatsParams = __Infer<typeof MigrateSeedExtendedStatsReducer>;
export type NextProblemParams = __Infer<typeof NextProblemReducer>;
export type RegenerateRecoveryKeyParams = __Infer<typeof RegenerateRecoveryKeyReducer>;
export type RegisterParams = __Infer<typeof RegisterReducer>;
export type RestoreAccountParams = __Infer<typeof RestoreAccountReducer>;
export type SetExtendedModeParams = __Infer<typeof SetExtendedModeReducer>;
export type SetLearningTierParams = __Infer<typeof SetLearningTierReducer>;
export type SetUsernameParams = __Infer<typeof SetUsernameReducer>;
export type StartClassSprintParams = __Infer<typeof StartClassSprintReducer>;
export type StartSessionParams = __Infer<typeof StartSessionReducer>;
export type SubmitAnswerParams = __Infer<typeof SubmitAnswerReducer>;
export type ToggleClassroomVisibilityParams = __Infer<typeof ToggleClassroomVisibilityReducer>;
export type UseTransferCodeParams = __Infer<typeof UseTransferCodeReducer>;

