// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  playerIdentity: __t.identity().name("player_identity"),
  sessionId: __t.u64().name("session_id"),
  a: __t.u8(),
  b: __t.u8(),
  userAnswer: __t.u32().name("user_answer"),
  isCorrect: __t.bool().name("is_correct"),
  responseMs: __t.u32().name("response_ms"),
  answeredAt: __t.timestamp().name("answered_at"),
});
