// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerIdentity: __t.identity().primaryKey().name("player_identity"),
  username: __t.string(),
  bestWeightedScore: __t.f32().name("best_weighted_score"),
  bestAccuracyPct: __t.u8().name("best_accuracy_pct"),
  bestTotalAnswered: __t.u32().name("best_total_answered"),
  learningTier: __t.u8().name("learning_tier"),
});
