// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.3 (commit 5836c268a7307f864b33636357b0869ecc40bc0a).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import CompleteOnboardingReducer from "./complete_onboarding_reducer";
import CreateClassroomReducer from "./create_classroom_reducer";
import CreateRecoveryKeyReducer from "./create_recovery_key_reducer";
import CreateTransferCodeReducer from "./create_transfer_code_reducer";
import EndClassSprintReducer from "./end_class_sprint_reducer";
import EndSessionReducer from "./end_session_reducer";
import GetMyRecoveryCodeReducer from "./get_my_recovery_code_reducer";
import JoinClassroomReducer from "./join_classroom_reducer";
import LeaveClassroomReducer from "./leave_classroom_reducer";
import MarkRecoveryEmailedReducer from "./mark_recovery_emailed_reducer";
import MigrateRecomputeTiersReducer from "./migrate_recompute_tiers_reducer";
import MigrateResetWeightsReducer from "./migrate_reset_weights_reducer";
import MigrateSeedBestScoresReducer from "./migrate_seed_best_scores_reducer";
import MigrateSeedExtendedPairsReducer from "./migrate_seed_extended_pairs_reducer";
import RegenerateRecoveryKeyReducer from "./regenerate_recovery_key_reducer";
import RegisterReducer from "./register_reducer";
import SetUsernameReducer from "./set_username_reducer";
import StartClassSprintReducer from "./start_class_sprint_reducer";
import StartSessionReducer from "./start_session_reducer";
import SubmitAnswerReducer from "./submit_answer_reducer";
import ToggleClassroomVisibilityReducer from "./toggle_classroom_visibility_reducer";
import UseTransferCodeReducer from "./use_transfer_code_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import AnswersRow from "./answers_table";
import BestScoresRow from "./best_scores_table";
import ClassSprintsRow from "./class_sprints_table";
import ClassroomMembersRow from "./classroom_members_table";
import ClassroomsRow from "./classrooms_table";
import OnlinePlayersRow from "./online_players_table";
import PlayersRow from "./players_table";
import ProblemStatsRow from "./problem_stats_table";
import SessionsRow from "./sessions_table";
import UnlockLogsRow from "./unlock_logs_table";
// Private tables — hand-written (codegen skips private tables). Re-add after each `make generate`.
import RecoveryCodeResultRow from "./recovery_code_results_table";
import TransferCodeResultRow from "./transfer_code_results_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  answers: __table({
    name: 'answers',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
      { name: 'session_id', algorithm: 'btree', columns: [
        'sessionId',
      ] },
    ],
    constraints: [
      { name: 'answers_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AnswersRow),
  best_scores: __table({
    name: 'best_scores',
    indexes: [
      { name: 'learning_tier', algorithm: 'btree', columns: [
        'learningTier',
      ] },
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'best_scores_player_identity_key', constraint: 'unique', columns: ['playerIdentity'] },
    ],
  }, BestScoresRow),
  class_sprints: __table({
    name: 'class_sprints',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'class_sprints_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClassSprintsRow),
  classroom_members: __table({
    name: 'classroom_members',
    indexes: [
      { name: 'classroom_id', algorithm: 'btree', columns: [
        'classroomId',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'player_identity', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'classroom_members_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClassroomMembersRow),
  classrooms: __table({
    name: 'classrooms',
    indexes: [
      { name: 'code', algorithm: 'btree', columns: [
        'code',
      ] },
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'teacher', algorithm: 'btree', columns: [
        'teacher',
      ] },
    ],
    constraints: [
      { name: 'classrooms_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClassroomsRow),
  online_players: __table({
    name: 'online_players',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'online_players_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, OnlinePlayersRow),
  players: __table({
    name: 'players',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'learning_tier', algorithm: 'btree', columns: [
        'learningTier',
      ] },
    ],
    constraints: [
      { name: 'players_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayersRow),
  problem_stats: __table({
    name: 'problem_stats',
    indexes: [
      { name: 'a', algorithm: 'btree', columns: [
        'a',
      ] },
      { name: 'b', algorithm: 'btree', columns: [
        'b',
      ] },
      { name: 'problem_key', algorithm: 'btree', columns: [
        'problemKey',
      ] },
    ],
    constraints: [
      { name: 'problem_stats_problem_key_key', constraint: 'unique', columns: ['problemKey'] },
    ],
  }, ProblemStatsRow),
  sessions: __table({
    name: 'sessions',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'sessions_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SessionsRow),
  unlock_logs: __table({
    name: 'unlock_logs',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'unlock_logs_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, UnlockLogsRow),
  // Private tables — hand-written entries (not generated by codegen). Re-add after each `make generate`.
  recovery_code_results: __table({
    name: 'recovery_code_results',
    indexes: [],
    constraints: [
      { name: 'recovery_code_results_owner_key', constraint: 'unique', columns: ['owner'] },
    ],
  }, RecoveryCodeResultRow),
  transfer_code_results: __table({
    name: 'transfer_code_results',
    indexes: [],
    constraints: [
      { name: 'transfer_code_results_owner_key', constraint: 'unique', columns: ['owner'] },
    ],
  }, TransferCodeResultRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("complete_onboarding", CompleteOnboardingReducer),
  __reducerSchema("create_classroom", CreateClassroomReducer),
  __reducerSchema("create_recovery_key", CreateRecoveryKeyReducer),
  __reducerSchema("create_transfer_code", CreateTransferCodeReducer),
  __reducerSchema("end_class_sprint", EndClassSprintReducer),
  __reducerSchema("end_session", EndSessionReducer),
  __reducerSchema("get_my_recovery_code", GetMyRecoveryCodeReducer),
  __reducerSchema("join_classroom", JoinClassroomReducer),
  __reducerSchema("leave_classroom", LeaveClassroomReducer),
  __reducerSchema("mark_recovery_emailed", MarkRecoveryEmailedReducer),
  __reducerSchema("migrate_recompute_tiers", MigrateRecomputeTiersReducer),
  __reducerSchema("migrate_reset_weights", MigrateResetWeightsReducer),
  __reducerSchema("migrate_seed_best_scores", MigrateSeedBestScoresReducer),
  __reducerSchema("migrate_seed_extended_pairs", MigrateSeedExtendedPairsReducer),
  __reducerSchema("regenerate_recovery_key", RegenerateRecoveryKeyReducer),
  __reducerSchema("register", RegisterReducer),
  __reducerSchema("set_username", SetUsernameReducer),
  __reducerSchema("start_class_sprint", StartClassSprintReducer),
  __reducerSchema("start_session", StartSessionReducer),
  __reducerSchema("submit_answer", SubmitAnswerReducer),
  __reducerSchema("toggle_classroom_visibility", ToggleClassroomVisibilityReducer),
  __reducerSchema("use_transfer_code", UseTransferCodeReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.3" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

