// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptFriendInviteReducer from "./accept_friend_invite_reducer";
import AdminRestoreMembershipForReducer from "./admin_restore_membership_for_reducer";
import AdminSetHmacSecretReducer from "./admin_set_hmac_secret_reducer";
import AdminSetPlayerTypeReducer from "./admin_set_player_type_reducer";
import CleanupOrphanedMembershipsReducer from "./cleanup_orphaned_memberships_reducer";
import CompleteOnboardingReducer from "./complete_onboarding_reducer";
import ConsumeRestoreResultReducer from "./consume_restore_result_reducer";
import CreateClassroomReducer from "./create_classroom_reducer";
import CreateFriendInviteReducer from "./create_friend_invite_reducer";
import CreateRecoveryKeyReducer from "./create_recovery_key_reducer";
import DeletePlayerReducer from "./delete_player_reducer";
import EndClassSprintReducer from "./end_class_sprint_reducer";
import EndSessionReducer from "./end_session_reducer";
import FixTiersReducer from "./fix_tiers_reducer";
import FocusStudentReducer from "./focus_student_reducer";
import GetClassRecoveryCodesReducer from "./get_class_recovery_codes_reducer";
import GetMyEmailReducer from "./get_my_email_reducer";
import GetMyRecoveryCodeReducer from "./get_my_recovery_code_reducer";
import GrantAdminToReducer from "./grant_admin_to_reducer";
import IssueProblemReducer from "./issue_problem_reducer";
import JoinClassAsStudentReducer from "./join_class_as_student_reducer";
import JoinClassroomReducer from "./join_classroom_reducer";
import LeaveClassroomReducer from "./leave_classroom_reducer";
import MarkRecoveryEmailedReducer from "./mark_recovery_emailed_reducer";
import MigrateCloseOrphanSessionsReducer from "./migrate_close_orphan_sessions_reducer";
import MigrateEmailsToPrivateReducer from "./migrate_emails_to_private_reducer";
import MigrateRebuildDktWeightsReducer from "./migrate_rebuild_dkt_weights_reducer";
import MigrateRecomputeTiersReducer from "./migrate_recompute_tiers_reducer";
import MigrateRecomputeTiersV2Reducer from "./migrate_recompute_tiers_v_2_reducer";
import MigrateResetWeightsReducer from "./migrate_reset_weights_reducer";
import MigrateSeedBestScoresReducer from "./migrate_seed_best_scores_reducer";
import MigrateSeedExtendedPairsReducer from "./migrate_seed_extended_pairs_reducer";
import MigrateSeedExtendedStatsReducer from "./migrate_seed_extended_stats_reducer";
import MigrateV3EconomyTriplerReducer from "./migrate_v_3_economy_tripler_reducer";
import NextProblemReducer from "./next_problem_reducer";
import ReconnectLegacySessionsReducer from "./reconnect_legacy_sessions_reducer";
import RecoverOrphanedSprintsReducer from "./recover_orphaned_sprints_reducer";
import RegenerateRecoveryKeyReducer from "./regenerate_recovery_key_reducer";
import RegisterReducer from "./register_reducer";
import RemoveClassroomMemberReducer from "./remove_classroom_member_reducer";
import RemoveFriendReducer from "./remove_friend_reducer";
import RestoreAccountReducer from "./restore_account_reducer";
import RestoreAccountViaEmailReducer from "./restore_account_via_email_reducer";
import RestoreAnswerReducer from "./restore_answer_reducer";
import RestoreBestScoreReducer from "./restore_best_score_reducer";
import RestoreClassroomReducer from "./restore_classroom_reducer";
import RestoreClassroomMemberReducer from "./restore_classroom_member_reducer";
import RestorePlayerFullReducer from "./restore_player_full_reducer";
import RestoreRecoveryKeyReducer from "./restore_recovery_key_reducer";
import RestoreSessionReducer from "./restore_session_reducer";
import RevokeFriendInviteReducer from "./revoke_friend_invite_reducer";
import SetExtendedModeReducer from "./set_extended_mode_reducer";
import SetLearningTierReducer from "./set_learning_tier_reducer";
import SetUsernameReducer from "./set_username_reducer";
import StartClassSprintReducer from "./start_class_sprint_reducer";
import StartDiagnosticSessionReducer from "./start_diagnostic_session_reducer";
import StartSessionReducer from "./start_session_reducer";
import SubmitAnswerReducer from "./submit_answer_reducer";
import SyncKeystrokeReducer from "./sync_keystroke_reducer";
import SynthesizeLegacySprintsReducer from "./synthesize_legacy_sprints_reducer";
import ToggleClassroomVisibilityReducer from "./toggle_classroom_visibility_reducer";
import UpdateFriendAliasReducer from "./update_friend_alias_reducer";
import VerifyTeacherUpgradeReducer from "./verify_teacher_upgrade_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import BestScoresRow from "./best_scores_table";
import ClassSprintsRow from "./class_sprints_table";
import MyAnswersRow from "./my_answers_table";
import MyClassRecoveryResultsRow from "./my_class_recovery_results_table";
import MyClassroomAnswersRow from "./my_classroom_answers_table";
import MyClassroomIssuedProblemResultsV2Row from "./my_classroom_issued_problem_results_v_2_table";
import MyClassroomKeystrokesRow from "./my_classroom_keystrokes_table";
import MyClassroomMembersRow from "./my_classroom_members_table";
import MyClassroomNextProblemResultsV2Row from "./my_classroom_next_problem_results_v_2_table";
import MyClassroomSessionsRow from "./my_classroom_sessions_table";
import MyClassroomsRow from "./my_classrooms_table";
import MyEmailResultsRow from "./my_email_results_table";
import MyFriendInvitesRow from "./my_friend_invites_table";
import MyFriendshipsRow from "./my_friendships_table";
import MyIssuedProblemResultsV2Row from "./my_issued_problem_results_v_2_table";
import MyNextProblemResultsV2Row from "./my_next_problem_results_v_2_table";
import MyPlayerDktWeightsRow from "./my_player_dkt_weights_table";
import MyRecoveryCodeResultsRow from "./my_recovery_code_results_table";
import MyRestoreResultsRow from "./my_restore_results_table";
import MySessionsRow from "./my_sessions_table";
import MyStudentKeystrokesRow from "./my_student_keystrokes_table";
import MyTeacherFocusRow from "./my_teacher_focus_table";
import MyUnlockLogsRow from "./my_unlock_logs_table";
import OnlinePlayersRow from "./online_players_table";
import PlayersRow from "./players_table";
import ProblemStatsRow from "./problem_stats_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  best_scores: __table({
    name: 'best_scores',
    indexes: [
      { accessor: 'learning_tier', name: 'best_scores_learning_tier_idx_btree', algorithm: 'btree', columns: [
        'learningTier',
      ] },
      { accessor: 'player_identity', name: 'best_scores_player_identity_idx_btree', algorithm: 'btree', columns: [
        'playerIdentity',
      ] },
    ],
    constraints: [
      { name: 'best_scores_player_identity_key', constraint: 'unique', columns: ['playerIdentity'] },
    ],
  }, BestScoresRow),
  class_sprints: __table({
    name: 'class_sprints',
    indexes: [
      { accessor: 'classroom_id', name: 'class_sprints_classroom_id_idx_btree', algorithm: 'btree', columns: [
        'classroomId',
      ] },
      { accessor: 'id', name: 'class_sprints_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'teacher', name: 'class_sprints_teacher_idx_btree', algorithm: 'btree', columns: [
        'teacher',
      ] },
    ],
    constraints: [
      { name: 'class_sprints_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ClassSprintsRow),
  online_players: __table({
    name: 'online_players',
    indexes: [
      { accessor: 'identity', name: 'online_players_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'online_players_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, OnlinePlayersRow),
  players: __table({
    name: 'players',
    indexes: [
      { accessor: 'identity', name: 'players_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'learning_tier', name: 'players_learning_tier_idx_btree', algorithm: 'btree', columns: [
        'learningTier',
      ] },
    ],
    constraints: [
      { name: 'players_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayersRow),
  problem_stats: __table({
    name: 'problem_stats',
    indexes: [
      { accessor: 'a', name: 'problem_stats_a_idx_btree', algorithm: 'btree', columns: [
        'a',
      ] },
      { accessor: 'b', name: 'problem_stats_b_idx_btree', algorithm: 'btree', columns: [
        'b',
      ] },
      { accessor: 'problem_key', name: 'problem_stats_problem_key_idx_btree', algorithm: 'btree', columns: [
        'problemKey',
      ] },
    ],
    constraints: [
      { name: 'problem_stats_problem_key_key', constraint: 'unique', columns: ['problemKey'] },
    ],
  }, ProblemStatsRow),
  my_answers: __table({
    name: 'my_answers',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAnswersRow),
  my_class_recovery_results: __table({
    name: 'my_class_recovery_results',
    indexes: [
    ],
    constraints: [
    ],
  }, MyClassRecoveryResultsRow),
  my_classroom_answers: __table({
    name: 'my_classroom_answers',
    indexes: [
    ],
    constraints: [
    ],
  }, MyClassroomAnswersRow),
  my_classroom_issued_problem_results_v2: __table({
    name: 'my_classroom_issued_problem_results_v_2',
    indexes: [
    ],
    constraints: [
    ],
  }, MyClassroomIssuedProblemResultsV2Row),
  my_classroom_keystrokes: __table({
    name: 'my_classroom_keystrokes',
    indexes: [
    ],
    constraints: [
    ],
  }, MyClassroomKeystrokesRow),
  my_classroom_members: __table({
    name: 'my_classroom_members',
    indexes: [
    ],
    constraints: [
    ],
  }, MyClassroomMembersRow),
  my_classroom_next_problem_results_v2: __table({
    name: 'my_classroom_next_problem_results_v_2',
    indexes: [
    ],
    constraints: [
    ],
  }, MyClassroomNextProblemResultsV2Row),
  my_classroom_sessions: __table({
    name: 'my_classroom_sessions',
    indexes: [
    ],
    constraints: [
    ],
  }, MyClassroomSessionsRow),
  my_classrooms: __table({
    name: 'my_classrooms',
    indexes: [
    ],
    constraints: [
    ],
  }, MyClassroomsRow),
  my_email_results: __table({
    name: 'my_email_results',
    indexes: [
    ],
    constraints: [
    ],
  }, MyEmailResultsRow),
  my_friend_invites: __table({
    name: 'my_friend_invites',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFriendInvitesRow),
  my_friendships: __table({
    name: 'my_friendships',
    indexes: [
    ],
    constraints: [
    ],
  }, MyFriendshipsRow),
  my_issued_problem_results_v2: __table({
    name: 'my_issued_problem_results_v_2',
    indexes: [
    ],
    constraints: [
    ],
  }, MyIssuedProblemResultsV2Row),
  my_next_problem_results_v2: __table({
    name: 'my_next_problem_results_v_2',
    indexes: [
    ],
    constraints: [
    ],
  }, MyNextProblemResultsV2Row),
  my_player_dkt_weights: __table({
    name: 'my_player_dkt_weights',
    indexes: [
    ],
    constraints: [
    ],
  }, MyPlayerDktWeightsRow),
  my_recovery_code_results: __table({
    name: 'my_recovery_code_results',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRecoveryCodeResultsRow),
  my_restore_results: __table({
    name: 'my_restore_results',
    indexes: [
    ],
    constraints: [
    ],
  }, MyRestoreResultsRow),
  my_sessions: __table({
    name: 'my_sessions',
    indexes: [
    ],
    constraints: [
    ],
  }, MySessionsRow),
  my_student_keystrokes: __table({
    name: 'my_student_keystrokes',
    indexes: [
    ],
    constraints: [
    ],
  }, MyStudentKeystrokesRow),
  my_teacher_focus: __table({
    name: 'my_teacher_focus',
    indexes: [
    ],
    constraints: [
    ],
  }, MyTeacherFocusRow),
  my_unlock_logs: __table({
    name: 'my_unlock_logs',
    indexes: [
    ],
    constraints: [
    ],
  }, MyUnlockLogsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_friend_invite", AcceptFriendInviteReducer),
  __reducerSchema("admin_restore_membership_for", AdminRestoreMembershipForReducer),
  __reducerSchema("admin_set_hmac_secret", AdminSetHmacSecretReducer),
  __reducerSchema("admin_set_player_type", AdminSetPlayerTypeReducer),
  __reducerSchema("cleanup_orphaned_memberships", CleanupOrphanedMembershipsReducer),
  __reducerSchema("complete_onboarding", CompleteOnboardingReducer),
  __reducerSchema("consume_restore_result", ConsumeRestoreResultReducer),
  __reducerSchema("create_classroom", CreateClassroomReducer),
  __reducerSchema("create_friend_invite", CreateFriendInviteReducer),
  __reducerSchema("create_recovery_key", CreateRecoveryKeyReducer),
  __reducerSchema("delete_player", DeletePlayerReducer),
  __reducerSchema("end_class_sprint", EndClassSprintReducer),
  __reducerSchema("end_session", EndSessionReducer),
  __reducerSchema("fix_tiers", FixTiersReducer),
  __reducerSchema("focus_student", FocusStudentReducer),
  __reducerSchema("get_class_recovery_codes", GetClassRecoveryCodesReducer),
  __reducerSchema("get_my_email", GetMyEmailReducer),
  __reducerSchema("get_my_recovery_code", GetMyRecoveryCodeReducer),
  __reducerSchema("grant_admin_to", GrantAdminToReducer),
  __reducerSchema("issue_problem", IssueProblemReducer),
  __reducerSchema("join_class_as_student", JoinClassAsStudentReducer),
  __reducerSchema("join_classroom", JoinClassroomReducer),
  __reducerSchema("leave_classroom", LeaveClassroomReducer),
  __reducerSchema("mark_recovery_emailed", MarkRecoveryEmailedReducer),
  __reducerSchema("migrate_close_orphan_sessions", MigrateCloseOrphanSessionsReducer),
  __reducerSchema("migrate_emails_to_private", MigrateEmailsToPrivateReducer),
  __reducerSchema("migrate_rebuild_dkt_weights", MigrateRebuildDktWeightsReducer),
  __reducerSchema("migrate_recompute_tiers", MigrateRecomputeTiersReducer),
  __reducerSchema("migrate_recompute_tiers_v_2", MigrateRecomputeTiersV2Reducer),
  __reducerSchema("migrate_reset_weights", MigrateResetWeightsReducer),
  __reducerSchema("migrate_seed_best_scores", MigrateSeedBestScoresReducer),
  __reducerSchema("migrate_seed_extended_pairs", MigrateSeedExtendedPairsReducer),
  __reducerSchema("migrate_seed_extended_stats", MigrateSeedExtendedStatsReducer),
  __reducerSchema("migrate_v_3_economy_tripler", MigrateV3EconomyTriplerReducer),
  __reducerSchema("next_problem", NextProblemReducer),
  __reducerSchema("reconnect_legacy_sessions", ReconnectLegacySessionsReducer),
  __reducerSchema("recover_orphaned_sprints", RecoverOrphanedSprintsReducer),
  __reducerSchema("regenerate_recovery_key", RegenerateRecoveryKeyReducer),
  __reducerSchema("register", RegisterReducer),
  __reducerSchema("remove_classroom_member", RemoveClassroomMemberReducer),
  __reducerSchema("remove_friend", RemoveFriendReducer),
  __reducerSchema("restore_account", RestoreAccountReducer),
  __reducerSchema("restore_account_via_email", RestoreAccountViaEmailReducer),
  __reducerSchema("restore_answer", RestoreAnswerReducer),
  __reducerSchema("restore_best_score", RestoreBestScoreReducer),
  __reducerSchema("restore_classroom", RestoreClassroomReducer),
  __reducerSchema("restore_classroom_member", RestoreClassroomMemberReducer),
  __reducerSchema("restore_player_full", RestorePlayerFullReducer),
  __reducerSchema("restore_recovery_key", RestoreRecoveryKeyReducer),
  __reducerSchema("restore_session", RestoreSessionReducer),
  __reducerSchema("revoke_friend_invite", RevokeFriendInviteReducer),
  __reducerSchema("set_extended_mode", SetExtendedModeReducer),
  __reducerSchema("set_learning_tier", SetLearningTierReducer),
  __reducerSchema("set_username", SetUsernameReducer),
  __reducerSchema("start_class_sprint", StartClassSprintReducer),
  __reducerSchema("start_diagnostic_session", StartDiagnosticSessionReducer),
  __reducerSchema("start_session", StartSessionReducer),
  __reducerSchema("submit_answer", SubmitAnswerReducer),
  __reducerSchema("sync_keystroke", SyncKeystrokeReducer),
  __reducerSchema("synthesize_legacy_sprints", SynthesizeLegacySprintsReducer),
  __reducerSchema("toggle_classroom_visibility", ToggleClassroomVisibilityReducer),
  __reducerSchema("update_friend_alias", UpdateFriendAliasReducer),
  __reducerSchema("verify_teacher_upgrade", VerifyTeacherUpgradeReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

