// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  playerIdentity: __t.identity().name("player_identity"),
  username: __t.string(),
  weightedScore: __t.f32().name("weighted_score"),
  rawScore: __t.u32().name("raw_score"),
  accuracyPct: __t.u8().name("accuracy_pct"),
  totalAnswered: __t.u32().name("total_answered"),
  isComplete: __t.bool().name("is_complete"),
  startedAt: __t.timestamp().name("started_at"),
  classSprintId: __t.u64().name("class_sprint_id"),
  heat: __t.u8(),
});
