// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  initiatorIdentity: __t.identity().name("initiator_identity"),
  recipientIdentity: __t.identity().name("recipient_identity"),
  aliasByInitiator: __t.option(__t.string()).name("alias_by_initiator"),
  aliasByRecipient: __t.option(__t.string()).name("alias_by_recipient"),
  createdAt: __t.timestamp().name("created_at"),
});
