// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  username: __t.string(),
  bestScore: __t.f32().name("best_score"),
  totalSessions: __t.u32().name("total_sessions"),
  totalCorrect: __t.u32().name("total_correct"),
  totalAnswered: __t.u32().name("total_answered"),
  onboardingDone: __t.bool().name("onboarding_done"),
  learningTier: __t.u8().name("learning_tier"),
});
