// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  problemKey: __t.u16().primaryKey().name("problem_key"),
  a: __t.u8(),
  b: __t.u8(),
  category: __t.u8(),
  attemptCount: __t.u32().name("attempt_count"),
  correctCount: __t.u32().name("correct_count"),
  avgResponseMs: __t.u32().name("avg_response_ms"),
  difficultyWeight: __t.f32().name("difficulty_weight"),
});
