// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Answer = __t.object("Answer", {
  id: __t.u64(),
  playerIdentity: __t.identity(),
  sessionId: __t.u64(),
  a: __t.u8(),
  b: __t.u8(),
  userAnswer: __t.u32(),
  isCorrect: __t.bool(),
  responseMs: __t.u32(),
  answeredAt: __t.timestamp(),
});
export type Answer = __Infer<typeof Answer>;

export const Classroom = __t.object("Classroom", {
  id: __t.u64(),
  code: __t.string(),
  name: __t.string(),
  teacher: __t.identity(),
});
export type Classroom = __Infer<typeof Classroom>;

export const ClassroomMember = __t.object("ClassroomMember", {
  id: __t.u64(),
  classroomId: __t.u64(),
  playerIdentity: __t.identity(),
  hidden: __t.bool(),
});
export type ClassroomMember = __Infer<typeof ClassroomMember>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  username: __t.string(),
  bestScore: __t.f32(),
  totalSessions: __t.u32(),
  totalCorrect: __t.u32(),
  totalAnswered: __t.u32(),
  onboardingDone: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const ProblemStat = __t.object("ProblemStat", {
  problemKey: __t.u16(),
  a: __t.u8(),
  b: __t.u8(),
  category: __t.u8(),
  attemptCount: __t.u32(),
  correctCount: __t.u32(),
  avgResponseMs: __t.u32(),
  difficultyWeight: __t.f32(),
});
export type ProblemStat = __Infer<typeof ProblemStat>;

export const RecoveryKey = __t.object("RecoveryKey", {
  code: __t.string(),
  owner: __t.identity(),
  token: __t.string(),
});
export type RecoveryKey = __Infer<typeof RecoveryKey>;

export const Session = __t.object("Session", {
  id: __t.u64(),
  playerIdentity: __t.identity(),
  username: __t.string(),
  weightedScore: __t.f32(),
  rawScore: __t.u32(),
  accuracyPct: __t.u8(),
  totalAnswered: __t.u32(),
  isComplete: __t.bool(),
  startedAt: __t.timestamp(),
});
export type Session = __Infer<typeof Session>;

export const TransferCode = __t.object("TransferCode", {
  code: __t.string(),
  owner: __t.identity(),
  token: __t.string(),
  createdAt: __t.timestamp(),
});
export type TransferCode = __Infer<typeof TransferCode>;

