// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Answer = __t.object("Answer", {
  id: __t.u64(),
  playerIdentity: __t.identity(),
  sessionId: __t.u64(),
  a: __t.u8(),
  b: __t.u8(),
  userAnswer: __t.u32(),
  isCorrect: __t.bool(),
  responseMs: __t.u32(),
  answeredAt: __t.timestamp(),
  attempts: __t.u8(),
  promptMode: __t.u8(),
});
export type Answer = __Infer<typeof Answer>;

export const BestScore = __t.object("BestScore", {
  playerIdentity: __t.identity(),
  username: __t.string(),
  bestWeightedScore: __t.f32(),
  bestAccuracyPct: __t.u8(),
  bestTotalAnswered: __t.u32(),
  learningTier: __t.u8(),
});
export type BestScore = __Infer<typeof BestScore>;

export const ClassRecoveryResult = __t.object("ClassRecoveryResult", {
  memberIdentity: __t.identity(),
  teacherIdentity: __t.identity(),
  classroomId: __t.u64(),
  username: __t.string(),
  code: __t.string(),
});
export type ClassRecoveryResult = __Infer<typeof ClassRecoveryResult>;

export const ClassSprint = __t.object("ClassSprint", {
  id: __t.u64(),
  classroomId: __t.u64(),
  teacher: __t.identity(),
  startedAt: __t.timestamp(),
  isActive: __t.bool(),
  isDiagnostic: __t.bool(),
});
export type ClassSprint = __Infer<typeof ClassSprint>;

export const Classroom = __t.object("Classroom", {
  id: __t.u64(),
  code: __t.string(),
  name: __t.string(),
  teacher: __t.identity(),
});
export type Classroom = __Infer<typeof Classroom>;

export const ClassroomMember = __t.object("ClassroomMember", {
  id: __t.u64(),
  classroomId: __t.u64(),
  playerIdentity: __t.identity(),
  hidden: __t.bool(),
});
export type ClassroomMember = __Infer<typeof ClassroomMember>;

export const EndSprintSchedule = __t.object("EndSprintSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  classSprintId: __t.u64(),
});
export type EndSprintSchedule = __Infer<typeof EndSprintSchedule>;

export const IssuedProblem = __t.object("IssuedProblem", {
  id: __t.u64(),
  sessionId: __t.u64(),
  a: __t.u8(),
  b: __t.u8(),
  token: __t.string(),
  promptMode: __t.u8(),
});
export type IssuedProblem = __Infer<typeof IssuedProblem>;

export const IssuedProblemResult = __t.object("IssuedProblemResult", {
  owner: __t.identity(),
  token: __t.string(),
  promptMode: __t.u8(),
});
export type IssuedProblemResult = __Infer<typeof IssuedProblemResult>;

export const IssuedProblemResultV2 = __t.object("IssuedProblemResultV2", {
  owner: __t.identity(),
  token: __t.string(),
  promptMode: __t.u8(),
  options: __t.array(__t.u32()),
});
export type IssuedProblemResultV2 = __Infer<typeof IssuedProblemResultV2>;

export const IssuedProblemV2 = __t.object("IssuedProblemV2", {
  id: __t.u64(),
  sessionId: __t.u64(),
  a: __t.u8(),
  b: __t.u8(),
  token: __t.string(),
  promptMode: __t.u8(),
  options: __t.array(__t.u32()),
});
export type IssuedProblemV2 = __Infer<typeof IssuedProblemV2>;

export const LegacyScoreBackup = __t.object("LegacyScoreBackup", {
  playerIdentity: __t.identity(),
  originalBestScore: __t.f32(),
  backedUpAt: __t.timestamp(),
});
export type LegacyScoreBackup = __Infer<typeof LegacyScoreBackup>;

export const NextProblemResult = __t.object("NextProblemResult", {
  owner: __t.identity(),
  sessionId: __t.u64(),
  a: __t.u8(),
  b: __t.u8(),
  token: __t.string(),
  promptMode: __t.u8(),
});
export type NextProblemResult = __Infer<typeof NextProblemResult>;

export const NextProblemResultV2 = __t.object("NextProblemResultV2", {
  owner: __t.identity(),
  sessionId: __t.u64(),
  a: __t.u8(),
  b: __t.u8(),
  token: __t.string(),
  promptMode: __t.u8(),
  options: __t.array(__t.u32()),
});
export type NextProblemResultV2 = __Infer<typeof NextProblemResultV2>;

export const OnlinePlayer = __t.object("OnlinePlayer", {
  identity: __t.identity(),
  username: __t.string(),
  connectedAt: __t.timestamp(),
  connectionCount: __t.u32(),
});
export type OnlinePlayer = __Infer<typeof OnlinePlayer>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  username: __t.string(),
  bestScore: __t.f32(),
  totalSessions: __t.u32(),
  totalCorrect: __t.u32(),
  totalAnswered: __t.u32(),
  onboardingDone: __t.bool(),
  learningTier: __t.u8(),
  recoveryEmailed: __t.bool(),
  extendedMode: __t.bool(),
  extendedLevel: __t.u8(),
});
export type Player = __Infer<typeof Player>;

export const ProblemStat = __t.object("ProblemStat", {
  problemKey: __t.u16(),
  a: __t.u8(),
  b: __t.u8(),
  category: __t.u8(),
  attemptCount: __t.u32(),
  correctCount: __t.u32(),
  avgResponseMs: __t.u32(),
  difficultyWeight: __t.f32(),
});
export type ProblemStat = __Infer<typeof ProblemStat>;

export const RecoveryCodeResult = __t.object("RecoveryCodeResult", {
  owner: __t.identity(),
  code: __t.string(),
});
export type RecoveryCodeResult = __Infer<typeof RecoveryCodeResult>;

export const RecoveryKey = __t.object("RecoveryKey", {
  code: __t.string(),
  owner: __t.identity(),
  token: __t.string(),
});
export type RecoveryKey = __Infer<typeof RecoveryKey>;

export const RestoreResult = __t.object("RestoreResult", {
  caller: __t.identity(),
  token: __t.string(),
});
export type RestoreResult = __Infer<typeof RestoreResult>;

export const Session = __t.object("Session", {
  id: __t.u64(),
  playerIdentity: __t.identity(),
  username: __t.string(),
  weightedScore: __t.f32(),
  rawScore: __t.u32(),
  accuracyPct: __t.u8(),
  totalAnswered: __t.u32(),
  isComplete: __t.bool(),
  startedAt: __t.timestamp(),
  classSprintId: __t.u64(),
  heat: __t.u8(),
});
export type Session = __Infer<typeof Session>;

export const SprintSequence = __t.object("SprintSequence", {
  sessionId: __t.u64(),
  playerIdentity: __t.identity(),
  sequence: __t.string(),
  index: __t.u32(),
});
export type SprintSequence = __Infer<typeof SprintSequence>;

export const StudentKeystroke = __t.object("StudentKeystroke", {
  studentId: __t.identity(),
  currentInput: __t.string(),
  timestamp: __t.timestamp(),
});
export type StudentKeystroke = __Infer<typeof StudentKeystroke>;

export const TeacherFocus = __t.object("TeacherFocus", {
  teacherId: __t.identity(),
  focusedStudentId: __t.identity(),
});
export type TeacherFocus = __Infer<typeof TeacherFocus>;

export const UnlockLog = __t.object("UnlockLog", {
  id: __t.u64(),
  playerIdentity: __t.identity(),
  tier: __t.u8(),
  unlockedAt: __t.timestamp(),
});
export type UnlockLog = __Infer<typeof UnlockLog>;

